---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-cert-pem-file-secret
  namespace: cloudflare
spec:
  encryptedData:
    cert.pem: AgBa5dgq/o+4lFeo9l2VkGS2Y8U3I3Zhu3KvRb+wmodnFaN4wV8YFl1Fas2raUBaJecGZFy7XNUYImVMV6SAGceDj1JcHORWk9D10xaReD6rvukUg3ArAkhlbqcKqfPqaG47VXZPOlZpBUixdzEgLuxYz3xwrCsrhPL/RrDvlwjj0dI1MvDb8Yx+CPNuXRU4f7FqHbLLK1odIVpVaT3IeSjmdthiZt1YO0IsZTfzbLZkogPGqQ0b/1gUGQ3CKL+tvf7UTSuzv3OmfeKYsQXIPw+Q4uutEm745jl0Lv8M7wI2VRw5Ga9BayJJRlzielAgfXRrXAj/XTlLV3brUBKnUHqG0BjMJ51WLTp4UPAzuBW3Lrd9JmsCsZ7oSmmDLFi7ix2O+LsluBeWj7qnsaM3FlJWUXUiFJr+WHAzUKXM4ciqtlA7scLJLZLBmgwFJgtJb2FHGVr7uzJ+m7ANNe7BRIVhI1iWy1gnDmkQvy8XyIXS2ZW5NB/FQI69ssORsPCW4Qsc8hy7WXhB0KvUAJpwyzclLkPQwIZRE/Cm980PUHeNVom2Th7/PIH4rP3erY/uhBeyw/wCyb+GxbYHxMgrEMnrPLLYd7fTxDD5h6fsmaPP0far/f64d8O9CQCY1u0VG/GOEMahjaip5zASvkhT5LANAW3ONnCRVC8wUAdW8lmfC1zbQ0r0XWS2tdjNTUxIycK7nAg0cE/p7RfqQwonXHGEsmpm2OzvIC6s6OcNg+UdJvGehV8D5XbX/HfQ0xMqAyyZP83sZ0PtamXa6ls/ym6rUahLM/l6vWRVdmwjawwdsizI0BnvCZrIblPM9UYR1AVbbMprgmtp8/EGmL4pL5uh6Dra1CNjkl5v8aD6qACtT814OfelACmIPrVkFwU583/JNwQXt2axuHmUQDg2MJ0D+RQn/cnDeRi8VkU+JfZvmPTcijoceGthe+1T2FunBfS3UDiSn+GQDZUVziCoOhLe/imC4Um7yxopFSA+iCS77xM8KY3GL9cXD0Nk27JkG2uE80ko8jq/NujgROMIZKqoUsijBvw1Fu4g9zQdpwTV5eWlDKnBKj5GHbE=
  template:
    metadata:
      name: cloudflared-cert-pem-file-secret
      namespace: cloudflare
