---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-config-json-file-secret
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgCPb0lZajo42GHn5wqBcnQvy5o02C7is/OGkM3KD3YM+ybOM23linqlZcdvApXwBzr5SLWIXQwTSyu7Jg/XdiuI2g606fMdZeo/nq+ZHpqd8tSVAQx5r15+C692Lgx9KzSJq+o+HZha3tHwTTEtWVmKPo7vCWqqi0jhVwGeqG0DneBG5o1AgNcIVht6h3pwkvf6HKBJqjbhSP8N5mTsr2EczccWEcsD4ZvW5qCkEWunhs+Su4nrzIBgp1JREHv8D1bt0KNKkPOhwLekWuLXHKHvcI45JPjJlgQTeDwJcY2gj4Y73giyQqhzaFwAWxY0TVTB6rfAY+V5l7LCCX/5i3SamxXjcRaf8qz1bmLlUPSkFojap6qyAPA16gIGPgOspxlBaMo5m8w20csjajgH16cbKRxy7Xx3aqtupNmu13wNitb1WDq/510aAZbYd29CbfjexwpBvfQ2XJve26tycls/qm2JpP9XSXdoTVgILCW0E5QSLHrxk2zsHdIxhajVYzfqgWoOe9e3ftDLHV0zXA4GR9+RhIJL00Nv2yqINYuCFHJ7OFS5ALTIGtJrR+Iczf023QNhmd0NoOYc0/D6c/QLvbuzql4IxfWRptsDAszAocU+458DAFr4lsgSqkOBWUeUb7jmvdhZ4X6oHVxKYEfNJWDd7xKVAiORL69upblIob77YRUcPILFxScGs1LPEuMYCX0sfJiFJ+0EHC9LcLCy3o6WUbyQiZzEtCa+DOnHJzwl21MuJeXvIPP3pXQQiZpSBcp4G70Y9mhpSvhKvkczUgzceXZQxTWBzKTy2sUMBgjYGwMwTgQ5Vfyh1qjkok5gQLX4wgWNT5NV5lhKaFjQ2YP2bNBVoA4aibZlJMQNrBUzeQUJkgqBN6dI2tdY+9zezWPnH1hwzW2w8uFRLKHbhBxaNT7+dmCsioMP3pP6
  template:
    metadata:
      name: cloudflared-config-json-file-secret
      namespace: cloudflare
