{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "garage-admin-token",
    "namespace": "garage-ui"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "garage-admin-token",
        "namespace": "garage-ui"
      }
    },
    "encryptedData": {
      "admin-token": "AgBaSOKehJ9RCMzFyxzwjsd2LL3gDk3PN7DvpxgB13Cz99wKBQRFxg9vilCF97fJxkZSAMH6C6XdGiZ6D2SD/MtuvvCQqoHgXD1kGNYFJ/mzYorXeUxix4o4gGEY0iV0uIxte/2pXgSG+q4SOMe99f9Pm6ukAj6OYsiZVX8orqZVck25bhamxpaY2neidym32MkmHkkrXvWU4Z9BSrnL4uoTun8jygnu6pFBf8UXumA1OK3fux77zX+5KzlmVXVyYWmo+Z0CZS7VgxYIZj6fRauyn7MgsrSm86FyPuvlh4E8VmNSHWg1HaetZgDOHRB/GEM9PSfzLU5or1srlxTBjp64HUskUct22W4D5qff+sSufzV2wJlSHSlU01TefSAvj12zZZkcedMwxeiEftPr2NwopDToYQQalphNVSDr1+xLH39jzIS0PHe/BpD9mOg8BVpJfcRTuwUcga6VzPLo712WMMv5j/ZwJD6iWigQ6X9J6oGdeWe8FNYI9ZI+LC4Smi8bPoknC1u8EKdQ7bGaqUiV6xDFvRZWGysl3TS1U359WId5lMVf98+59buka+sLK5v9A85w9vh+pdpSu/vcNs5QntOzcGCyIB0AlIaiNQzlMFoFADaBhJO+5CPNFDcN3uCCP9+fSuhKodCUBrUNX8Bf3VPzssV+yPWnIXXZi54zb5UH4i/fkgWLJjMi0+gkv4+dC2X53lKzIWUz+wVut0qi7NZbvarpej8w7ljtksijDaSEIuxwfLXQN/YQbTTm6oyp0IKUxrxKt6gsixUkiTGN54046w=="
    }
  }
}
