---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBdDFHR2RdxGx/KjEX7rcZG41VN7OsgVq5mPDDYlGlQu9t4/+zZGBlgr+bIcv+VIwaMqZWCI1XxPA4o7nA3MXkzWFOPA4J/ok8g+KGLLS7ZfOM3HT0Mirhjbni222VHryvP/iXoXT34HWGimw9Zx87BqGcEGuqXTDuRRkZTOKmDHzXvMMoOCKTfRwRBAPOfEMrHMZ6XmtiJi7Q+Ai+T8sMB2H0J4a9e8fM/3pkzSmYoIXWsjtemxecDgEkV/cFqoBbl69zZICxtyZhWeTQlUWPnVIcMY8+tqPg8jBbWa0cnXfymsEeycU/HwpQ2OivZz30fdJeBgrYgoyMeQIH4UJ7CofnSrJxhnp8hhH6HSakYLm7aNtYcv2Wd2NHU9IrBAqzRtIAYDfYkEbF88AlI4ZSDVtWRS/TcRVp9F7Hf2KQ86mPoop16IU6OH0sUjDFJJgujiNtlYepBfEx5PmusgxIB12dZ8DVOsOcCNBhGRZnhEuQXVdM0PzvJ6uztrVreQhAJiBqBGGlxQogFIIkniNA6K5nFktj/L8m9iUxepu277KvCde+TwPaiCZxDWQX0rbmUmf0Sb5jYYYCBzedShP0WRi3+1OMSiAIp7dldfTk8pWyPsRnH2nC1MxV2ohs23lMDoYz2OpoFkIrycpbCMWDHG94W8V+AgyOtaBzRYLykg5Mf2l9KVQbNqsAYkSZErxfw0a7oK64lP4hjMcBcs9V3DA==
    client_secret: AgAlyWinLfs0QUbLPWOb3XadJUn6vS3U39C+dhbzRo21/lWgrmDq7T5ilbXN1a7CvOwfblvzGteJwodTrkl5rdIEZk4ZVjTXDr1hNlCQ4p5gWX2mn8BmGACB8sSmlTVJfieeDDTJ3Qz70t5u9Y0mLEWUnA71+yUbKxbbngVIp54LVlrY+7U6Rf5cEDWujxjQ/+CyyOzS5ihY6TpV6Bgq8NyNMxZlvdkoc/lZ/lmbYmbh1PwC0TDe9u051BfNmJawMytBs/20CsEWOc6J6NQGvFVPc0vF/DpmPh26ImViOtUUYEOzEzn4yTaNv/qsmGUXLL9iQ+y5JOFZ7c8UrV2EliFphLYYiIeY40bAucE7a5SEct3B702hkList2KuZjxNP6y5WC9+nU66UzKUK+/irWvBrJf56RMysqIXxvv0inwVAypQcwA1CriI0iEb9zaZWpGpzlJnQ7WlxisvhX4fYSFYF3Er42Ki5JKjPxJEHiEV9Hq3UfizjKeoTsPCFR9he4SommlB6eBZguTmzsJjMhATZBcxi5WBzq47Q795/YV9zNMzqRdexAmNmi3UmRMxfrpngZaA03Jk4yuJivcveck+ecnu/3Y80762UtWs5p+bEXKEHv1ZKSRIyf31KXQ38G0Wxwtm/4P+xIiXdBGX2vMivgTzDuGD2FwASuiFjCMs+HvxvZt8hmDXGXVuFv0qS+7Pa0vLWDhmINdDpLt4zw0LSC3VUfRZ7q5ldKwAoxaIbMFdYAr3EBmBNoJYsgqPo9hpX9iuQXpztV2Y+z02FZmn
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
