---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      version: "1.12.x"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  targetNamespace: longhorn-system
  values:
    networkPolicies:
      enabled: true
      type: k3s
    csi:
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1
    defaultSettings:
      backupCompressionMethod: gzip
      systemManagedComponentsNodeSelector: "storage:longhorn"
      defaultReplicaCount: 2
      guaranteedInstanceManagerCPU: 5
    longhornUI:
      replicas: 1
      nodeSelector.web: "true"
    longhornManager:
      log.format: json
      nodeSelector.storage: longhorn
    longhornDriver:
      log.format: json
      nodeSelector.storage: longhorn
    persistence:
      defaultClassReplicaCount: 2
      defaultDataLocality: best-effort
      reclaimPolicy: Keep
      volumeBindingMode: WaitForFirstConsumer
      migratable: true
      defaultNodeSelector.storage: longhorn