---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: home-oci-tofu-source
  namespace: flux-system
spec:
  interval: 10m
  url: oci://ghcr.io/andrewthomaslee/home/flux-iac/tf-source/tofu
  ref:
    tag: latest