---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: tofu
  namespace: flux-system
spec:
  path: ./
  approvePlan: auto
  destroyResourcesOnDeletion: true
  upgradeOnInit: false
  alwaysCleanupRunnerPod: false
  remediation:
    retries: -1
  interval: 15m
  sourceRef:
    kind: OCIRepository
    name: home-oci-tofu-source
  writeOutputsToSecret:
    name: tofu-output
  fileMappings:
    - secretRef:
        name: tofu-env-secret
        key: env-file-content
      location: workspace
      path: .env
  runnerPodTemplate:
    spec:
      image: ghcr.io/andrewthomaslee/home/flux-iac/tf-runner/tofu:latest