---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-cert
  namespace: cloudflare
spec:
  encryptedData:
    cert.pem: AgAbjSaIHL0IGLlbbTsHwvwyh7vYj75GCG7buLnyVWhoZgejrXO4pJMIL9nbi3KAzxUp4x0FmPgrnD/geYY09cwclVk6D57/W35tzCNWtpvNpojNEZCjPsDns4K4C7KMiVQTQGZveJzIxRy6UDxMe1RL3ob6G4qcloHTpng40z2yqX367g6//Hnx1rDybgD99iamjp7xKfa/Sq39G0MPKvDuxibZTM8tH/xIVKmH0ng9BtVIPPvrRVf/3lBhpayrxhNYySfNPXs770tudOuUfss0cqkJ2xrbsTzQytoyBN8Kqg1Y3jhiJHW9Xd1rl6C8eNZ+iAvUR45o5GXOGbdtgpo12SpEXk0yAl8TD3Ex+NbvbU8r4vNKU79BSgoVPElHhaP+Y/nTxGxldVTzZeeTyKKHF2OSHu7GpyyixuOS0CfNstpT0tmp7dOPCVZC2VWHPoEYbuU0bXDd79Zhg6eSEhQqLv7IqEz+ZvzTPpbf5HHnH/+Dx71yPqvE31gp6/It5kx0A5St7V+VVX7xA7s8VJpacgzvb3gahm2wy8eP+1x1vuorOjvr/aQbqQFOr+NqQWW05ghSBLQy5OOfSzn5YCZkjJN4JZ33ARQNMHXigkg9clBcjOO4hCDgl8xnsh+KgMhgLgh5lCVUwB/3M+MTxE5Hh5Xnlc8VqmyIPo5s3NnKzq0u+rKnHINhjG8sp+Iy7DbBDZMrH2Uv2b9k1z2wuHaPFzRoYw7SSZKzP6oMyBX6NWi8TzDCQK5K0kp8a7494QBzpk+/Xmquo2Y9g+VBSO0AlnErtIFpt8KuOqtslOe0Z10bwSO8vCGhZYQW3cZqrvmNyu7HQfKlqLRsGBGEdBB5QCrfVHyhOa9js/UK8UQyHFex3/cTqyGbOxwhYk/UPkjls6QhzJw7DTaUl7ADXdVxgxc9Ql4LIMNW0aGpcUlV1T+B8LTXc5nUQGpTA9oqnYuAXwK6EtfewD+hWNgCAiqb+pXJNwuCuq4KMU7Dv9BRBel15FytMCLhy6/kyjTKJyIPDdAgezhFX0OG/x4t/q0OHzfhpJe+hlWx0diYS7ebr+VdONj8NP/RqAE=
  template:
    metadata:
      name: cloudflared-cert
      namespace: cloudflare
