{
  "apiVersion": "v1",
  "items": [
    {
      "apiVersion": "helm.toolkit.fluxcd.io/v2",
      "kind": "HelmRelease",
      "metadata": {
        "labels": {
          "kubenix/hash": "daf4d4f8d39bbb577fa700677dcbd9e08ac10633"
        },
        "name": "cloudflared",
        "namespace": "cloudflare"
      },
      "spec": {
        "chart": {
          "spec": {
            "chart": "cloudflared",
            "interval": "24h",
            "sourceRef": {
              "kind": "HelmRepository",
              "name": "cloudflared",
              "namespace": "flux-system"
            },
            "version": "2.2.7"
          }
        },
        "interval": "24h",
        "values": {
          "ingress": [
            {
              "hostname": "whoami.andrewlee.fun",
              "service": "http://whoami.whoami.svc.cluster.local:80"
            },
            {
              "hostname": "hubble.andrewlee.fun",
              "service": "http://hubble-ui.kube-system.svc.cluster.local:80"
            },
            {
              "service": "http_status:404"
            }
          ],
          "resources": {
            "limits": {
              "cpu": "200m",
              "memory": "128Mi"
            },
            "requests": {
              "cpu": "100m",
              "memory": "64Mi"
            }
          },
          "tunnelConfig": {
            "name": "home"
          },
          "tunnelSecrets": {
            "existingConfigJsonFileSecret": {
              "name": "cloudflared-config-json-file-secret"
            },
            "existingPemFileSecret": {
              "name": "cloudflared-cert-pem-file-secret"
            }
          }
        }
      }
    }
  ],
  "kind": "List",
  "labels": {
    "kubenix/hash": "daf4d4f8d39bbb577fa700677dcbd9e08ac10633",
    "kubenix/k8s-version": "1.35",
    "kubenix/project-name": "home"
  }
}
