{
  "apiVersion": "v1",
  "items": [
    {
      "apiVersion": "v1",
      "kind": "Namespace",
      "metadata": {
        "labels": {
          "kubenix/hash": "82bdadfdefa5a1d1e1f20fde316cf0a16218ff13"
        },
        "name": "cloudflare"
      }
    },
    {
      "apiVersion": "v1",
      "kind": "Namespace",
      "metadata": {
        "labels": {
          "kubenix/hash": "82bdadfdefa5a1d1e1f20fde316cf0a16218ff13"
        },
        "name": "tailscale"
      }
    },
    {
      "apiVersion": "v1",
      "kind": "Namespace",
      "metadata": {
        "labels": {
          "kubenix/hash": "82bdadfdefa5a1d1e1f20fde316cf0a16218ff13"
        },
        "name": "whoami"
      }
    },
    {
      "apiVersion": "source.toolkit.fluxcd.io/v1",
      "kind": "HelmRepository",
      "metadata": {
        "labels": {
          "kubenix/hash": "82bdadfdefa5a1d1e1f20fde316cf0a16218ff13"
        },
        "name": "cloudflared",
        "namespace": "flux-system"
      },
      "spec": {
        "interval": "72h",
        "url": "https://community-charts.github.io/helm-charts"
      }
    },
    {
      "apiVersion": "source.toolkit.fluxcd.io/v1",
      "kind": "HelmRepository",
      "metadata": {
        "labels": {
          "kubenix/hash": "82bdadfdefa5a1d1e1f20fde316cf0a16218ff13"
        },
        "name": "tailscale-operator",
        "namespace": "flux-system"
      },
      "spec": {
        "interval": "72h",
        "url": "https://pkgs.tailscale.com/helmcharts"
      }
    },
    {
      "apiVersion": "helm.toolkit.fluxcd.io/v2",
      "kind": "HelmRelease",
      "metadata": {
        "labels": {
          "kubenix/hash": "82bdadfdefa5a1d1e1f20fde316cf0a16218ff13"
        },
        "name": "tailscale",
        "namespace": "tailscale"
      },
      "spec": {
        "chart": {
          "spec": {
            "chart": "tailscale-operator",
            "interval": "72h",
            "sourceRef": {
              "kind": "HelmRepository",
              "name": "tailscale-operator",
              "namespace": "flux-system"
            },
            "version": "1.96.5"
          }
        },
        "interval": "72h",
        "values": {
          "apiServerProxyConfig": {
            "mode": "true"
          }
        }
      }
    },
    {
      "apiVersion": "source.toolkit.fluxcd.io/v1",
      "kind": "HelmRepository",
      "metadata": {
        "labels": {
          "kubenix/hash": "82bdadfdefa5a1d1e1f20fde316cf0a16218ff13"
        },
        "name": "valkey",
        "namespace": "flux-system"
      },
      "spec": {
        "interval": "72h",
        "url": "https://valkey.io/valkey-helm/"
      }
    },
    {
      "apiVersion": "source.toolkit.fluxcd.io/v1",
      "kind": "HelmRepository",
      "metadata": {
        "labels": {
          "kubenix/hash": "82bdadfdefa5a1d1e1f20fde316cf0a16218ff13"
        },
        "name": "garage",
        "namespace": "flux-system"
      },
      "spec": {
        "interval": "72h",
        "url": "https://charts.derwitt.dev"
      }
    },
    {
      "apiVersion": "apps/v1",
      "kind": "DaemonSet",
      "metadata": {
        "labels": {
          "kubenix/hash": "82bdadfdefa5a1d1e1f20fde316cf0a16218ff13"
        },
        "name": "whoami",
        "namespace": "whoami"
      },
      "spec": {
        "selector": {
          "matchLabels": {
            "app": "whoami"
          }
        },
        "template": {
          "metadata": {
            "labels": {
              "app": "whoami"
            }
          },
          "spec": {
            "containers": [
              {
                "args": [
                  "--port",
                  "8080"
                ],
                "image": "traefik/whoami",
                "name": "whoami",
                "ports": [
                  {
                    "containerPort": 8080
                  }
                ],
                "securityContext": {
                  "allowPrivilegeEscalation": false,
                  "capabilities": {
                    "drop": [
                      "ALL"
                    ]
                  }
                }
              }
            ],
            "securityContext": {
              "fsGroup": 1000,
              "runAsGroup": 1000,
              "runAsNonRoot": true,
              "runAsUser": 1000,
              "seccompProfile": {
                "type": "RuntimeDefault"
              }
            }
          }
        }
      }
    },
    {
      "apiVersion": "v1",
      "kind": "Service",
      "metadata": {
        "annotations": {
          "service.cilium.io/global": "true"
        },
        "labels": {
          "kubenix/hash": "82bdadfdefa5a1d1e1f20fde316cf0a16218ff13"
        },
        "name": "whoami",
        "namespace": "whoami"
      },
      "spec": {
        "ipFamilies": [
          "IPv4",
          "IPv6"
        ],
        "ipFamilyPolicy": "PreferDualStack",
        "ports": [
          {
            "port": 80,
            "targetPort": 8080
          }
        ],
        "selector": {
          "app": "whoami"
        },
        "type": "ClusterIP"
      }
    }
  ],
  "kind": "List",
  "labels": {
    "kubenix/hash": "82bdadfdefa5a1d1e1f20fde316cf0a16218ff13",
    "kubenix/k8s-version": "1.34",
    "kubenix/project-name": "shared"
  }
}
