---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-cert-pem-file-secret
  namespace: cloudflare
spec:
  encryptedData:
    cert.pem: AgBsFclWqc7/IH72gwQ5SOLOtbDLKN233+RIsuetsyMhxqY8Jqu5Mmk6PwivQWN2P/TsURdfvtfDSYuv+iLrNRpSB/ZpxOLfnIrLRw1qpgAaGviJhy/BHtA5YbsbeXynuho+sBsE3m9ajdgLQ4o/eTRdtML7xMiM0YD8idkViEBGa2sDfnzp+V3O0UM3sn/4MNF5jMhemm4gtyYqUIA44at4o8popHF1FH5HUwBOP/K0lAI3VdO0AFsufC81slIA3arJp7DF1Jebi+RashEEgGrBpS0IwyiG4pQhmvaQrp9X+oNWiRBP7p94tC1xV7n7LtO5lOmvJNyhJHlvimHoIQoqlzpKtqYA4rjkOzo/rNKevFLz15/UyqefQGQxbQTmqf+L017VLCNLw7uCq+zw3IxwRH2Bl+Ftu5H0GgCh5LOkeI1lx6qguzkbw0cuSOg5UHfoRdnqZiCaSx9f84MD/AkyGWCm0rft/xqo0HUBcG5pGmNh5k6N0FflRtYI8BAzAgzWVPDj7XCcU6jH1NhpZgBoqxg8NapLMQ5iwvB/ayhEXu5rhvBzaDizkmJCPDHejivX9cni1bWAKabNJpGUnikfI+qOaMVZPWc742ssHbijHBzbmsSG56PtXIYqyn3pkrit9CdLx6RLLdy82AGiOwLweehyO3uBST3PuKyGxPVi7SgvRCus6heA43Ck9tfKe3Fflns3MjtySS79Ff0qDVlTSMHAmIFtt/a3f5M13KeXF7XYEHTA08/73Z2bTGenUctuIoQYMfypzuVhbwJqKfduBXBhmrU/9R+O3N/BLDdwhaGcorZCNNpEe428xoZcbrb0kiPLBcW1vTLDLCSLqRX3ZUi9ctyBFPzEGdZvK08+3RSzs99L9PiE8W398t6P06Iorbodleu4Bq7YnyqhXfZ/zDSYrCK+pcoAo6cSSSU09ck1jKsMr/oOU7HjTnodS6SEep0bLQQ3fCwzFq72bJUoMqrFIUV1XOGYOWg5lmcirEeJ+3SDWDXeA3PdgOKXmeXNM3uPZ4dNysxkWtMHtvrI7XzGYQ1phIXW/awZJQweUimc30dMMkcGp7I=
  template:
    metadata:
      name: cloudflared-cert-pem-file-secret
      namespace: cloudflare
