---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-config-json-file-secret
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgBwuNu627/Kbg455m9XTL8GKbjVeJfM9lPwkAkp2WyGrKRAY2uKETbu0N1yDo3uafikOGkDR0+fP2IqOc/K8tRQB63WyV4VwySaAI41Jb3ZduZtfuTXlG6diCb9wwmq54NKmHpLTDoG+rPQH/ehco2FduGxe8Hogud71MzY0TUqe6Z6uBw+jMpQwQdcAu3W23UoR63GmtXMa9Tn2WpKJaG5EGqNuVRerfD3jyooQnxHgWlJYKI3by3R0qskk70pJ9aOrBkMhR+g5LI0u9/DmdyIt/FTPgy6j3YModRyinn/tQFfwWp7siXfA5od8LZuS8kgiWBJfulwl2C2JB3cQmdr97c8LG0Kttdgnyty2A5+LaKzoAbl08KxLW3L2FkA0gU8c29PQRF1Zqx0BsrPrkP/shkHROTcYnn0cwAwEOm3N1ikqqQtMaQmQSGgx64XhZ/f/s/ovvc9FVwY8pRps9hMBTegNfvBfvU2hwKIgwL5L0XUUrNbq7m4aKx2gEHaKKoL3Lm2xB2GXTtJ4xRdboBuuRxD2lOI475UR6yPWUsUW4o9ozJRQceIJnd1fq+7gmAKvMZf4MgVmwATBv4yTvJO/3bx1RNmYQml0tOescg50UA2E8O5DdlYPcIn+ZJGEjMWXyEfnXSr9aqyCgr2LQBnus4DeW+LZQceD7qxBAY9IcB39KcDTyCb6Z/vetZkNtcT5P1gtKe2j7aCzbJf3+PZkBxCz2yTtufg2cxyp69v3ZvzAJFgo6LWtOIlusDaPHwuQXEYoqpJaGamG9zcYBwKHJBuFmQl9saVAvNjVueFoeuCBT2yVY/Tcq9+jnUrVhb4UDeXIRz14SxJ3Lg4291TJSph4svSotkL/vE4enS6d9p/BBvphm8fFJqDvzKhqwZpygHEeNobGSe3djFvCS/PcCBm90HkO7RmuTBd8chR
  template:
    metadata:
      name: cloudflared-config-json-file-secret
      namespace: cloudflare
