---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAFf8HZXuk5SnDDR+Zs5oNPtSGymtCz+804gvV1U7Tnv4+CVOtPEe9qUeL+iSGGGUSALATdT8cSqBwMNNscvLpOttJNCOoe65H8g52GqJw4FLnNiA2Vzxn4wmHAzJ5lS1TjmBPq8MmN+hWciclgtHUOp32EjaEjBnkZ6h1zmyPyeb8ECb4RZ8Th3ekiV3ettoq3wzeaGUORuCGoibUFG3P8Oo2NOqmetmmDuAkJyF37oVH8sQF38+VL/7FTNOxYoqDwI8jrq8DqD/LCrZHSGcNodwkUHh5eZQuD8zBZuHNmyrhAP/lFmtw2FP+TM7sikmujIoTYw0oDjmGK5OarMnfy56gnVJPceLVV3yWtyJtQ78n4dkosJGhIb1ZcMm1VrBIamBuCOt+7j6odXFmQKv4JJ06TyGPlBIyE/58d9OGXWmlA4zvGL9PoKHtDZFvYgfU9LYlpUDJP2nyUWYkKghgsqAQmErt56KNBARCfwsk+gXxz+Sxu91XuvFeNtbZ+m/Dv5heXaUyXky9rFDaDyT+LjuTrqLQNmmum42sQ+MJei1JThIq4qFQ1HJjx3HckcMJ2WTHifNZ3Q3FqpovGozT1p4Z4LvB41TJCM+3sK3DGRWITYdeKe1dkFBFnhNRDaOgv1bzEtARUI63dk90dfpmucVwAZiY6QbMHKCK8bM+ouEI1DAAdE5/pm3IMbrfxV3fp+baPR7KgHetHP0GPXxXzAiE4
    client_secret: AgC2V72uBR5NPUPr00vXGLU9rrhTLjuOlHt0zmQzFl0/DDPfCHGwBRyiiuBi6eOAqSiHBAAcIQzsE/XfCiz4jYLDQVJkaV/YOBphyPEaVoLApd+7PcvyftpE6aWAxYLmNDlMRiGcptW4QD3P5X83G57C9pjhg1KSeK4d09EEs+naqa8hKd08lsvTZBqh1kUjccANluhWpq8Jb8yzlnkzMJrcwz126H8O1j+5O9r4dP5EzSCpPpBzLY7M3Oh0EMOP/6FyH3VAAGWfU4oMOnCPysnxE41KU1S5H1YzqMWJ8wSx3fsX1+8CYHqxWVUW+9PdNC1taacwcmK1558VoAwYyEXuBTfbpf+HqeEuNUrJuaS4/Arr7AYq3P5scNeNFwpvElYfpm038SlKfgIux5KayjAH12kn3fM5Ofo+x+4Vt3g+zY1exNCGc9EhDCCckfJ8mMBSFwrTD///ISwWKvB3+0lmrIj/M1ku9uYKkOU1sCt4IgWSoM7lkxxBuiPjyQ9LajYD6ISAuE75yVGj9KWkXLmHc58dMoWHum8OhW0fZdNLY+vyk5UQnSf5ryS3Y6AVmYzFjwDRpumPp8grRVrcA7I2VEK9ZvX+bziuOvXRm6HJUHXz9RcVK8aHz/1wYrssfg4VqNYbG/wKtVtCLLibds3QhuQrrM+DzhLZmjw7trZUYEcwYu2iXbFVPxXLRL8jBYHSXwtoe0Y5AlR3zZ6tevdPWJVnbXPmVz/RsVCocjjCi4miiCqVxiIa1RBEsnRJsRFFmwN3tZyiiJ6UFja+DAki/nY=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
