---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgC7Y6k5NJ8ONA6XqV3EDRrT+B+QB4+gkLAYXtoOMUasZ9wH8Kx8j48DOwovs51VscN85pWMeQkzonB7XRHx9L6sMT66JQHQXqGsOE7u7M4z00HctrxiwlGu84hG6ffvgq+bQLdDCwfs9kACsVrHWNZJOuurPp5PqQUFPPh7g533UrN4EX14IgJ8NmxHcKF8wZuRntzyKG9IjdXVKcKP0rtYIsmWDM3xOAc1CJRaUqBNVum4smArOvk04aC6xst/B4dWmGHznU0hRkkltQzryXrr9tGxlCFQTgyFR9T1gaVo9SQoKiBMz0MgD1/VWvopH+F6zwG7vS9NAZB70oeEkHdZ8ZjpbzL7kg37qWLTKizHRUuGxvnCb6wxFnUNt55Sthm8S11Lpv4G1/iDv5aDBW7dxuNF8/yUnc4Px3HvbsOhVTpGqNJfAvTPjOzmo0tOMABthoxt3Pxg8u0F/TN1mu7siP4RdqG9C1FA+DSf/UN/IZivUVrgzSthE61biTFap765HaLUXfTRvp6muxm9GFnI7G7bbTH9gOkipL7fpC2zlMhfpRNgeMgMfbGmKyLQc2rTSS+jD8ahKK8mGyZTCODbjOanku8AgWKd6tg6ifOszAhg9K0JYKX/m31FjCojF13QwYJVc2fWwYvUPLe1lCYczDV0DvLpceKvK7iIjM67XQtaS9lbdIKeFfyl/p2GNO04V9wWOTItZ+FfopOjeQtY+w==
    client_secret: AgCvvwhRvGqIU38Mi+PrGO1SDlnkyk55fzh/KQPxhXVhyEX2e/ioJ9wMJ6viWYFo69e+KsvWFxw3FAiXbKgz+VpDyGwSbhL446u+ISOEVSwBNH5mc67H3mOF1y77zaNkv4kVyc4YBB1eCmgDvUnL6lfYZRntlICtxJrdKrk6K4UB6lzHZxJQ0i6qfyolLg5nkAnax0fGqKnV4uZOpdPRlucli4X9t0/sOXtiY0D7Vuxwwy7jiNUVowCrMzQCWOMIQx5YMcfRYo2nDisV+zIvjaU/CfpJdHu0qu/B+oWqrQpuD2YvYax0zpwo7DYUGQXpcwykaqkMwu2MPHyaTxUOenlC5Im3QaX1unnKw/r5eGTBh/KF4hGKc35kNq13UzhLb7iy4n7ahH2qxhXDWQj1MMeR28Gg5TpyVv1Q4YMwTV82O96s2QQEeXm2z7AM+1CnLYLf56JEO6gRX8+oeGcKBG+Vflm9ZhybKL/5PnR3YbL+QF4cbRGzbaqNKLStvRXCiIP8aVb6Wq3NmCeerka+M0KvKwxSPhESE7wUw9ODlWcdapinW0XoxIgWWhUNUgzE6OZhVXK3J6/Aka6vkts/S3Zv/AgDrZELsbuuFaW8RkAPJaC9fSlxoi6nOyr2G7GsjPAOjcz7N3Xg5tQgKKbrOOpwefgmPM8YLeOBSjPHMBJoIcnRsuPnySS+8ndDpEe5HIOfdlqPWWCrkMmvN6ikfIQbIffUbUexIghmvjTtumZr7XrvolnLuG4ra8GU94CDS7l8WEI397dPTTBJt1OGtvxD
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
