---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    clientId: AgAMa34m7aMGWjarUTd4XMqktZlqDsZcg9SxBPkVHWZjdOGwEu7AygCcHie3XBiW2j++pmy5Fgj8pXDXk2hMRuKe4GiSpAbmqBtwoEWcD44UfCogPdPzWK7SJ3acqUEsa5x3DSrrrcckkahtokRimLSMzD9/GRuFbcOVJUwJjB3C3oLeBvssRCORbXJVL0ikf6ZgEizkkghWhbYJDphwZLj48lcP+qs8WOoOy5jiv/O3VO7qufsXEraAJNrReWTd6YNQz40VC113ltL8h7RGe1soVi7OV/vbvOSU23ypCkXIDT8F2FMQSKXN/mHz6lPV75MAbhVFgaSk6oEb99Q7CpFHQTy9ITYJQzDZVgjfsGZqofBMP+E+GCA96iqjPwqmsSKyZBCbTo4sLmG9a/gFqPawUWsFgdaLa1abDtOX9gyjCvFeDAjxKUulyh3+zLFOeApJBmMmPkpUud5eud7x20/5VPLufPjV3Tb95Nwx3zex8foaVqKE8dZ+TU1QSDDL4WrSkAxOQO6tjKNcpsudV9HSon2aClTaIFMIjYRO8w28/J9Fl+/L0O3HP+GENhAJ8kH6NTMmiwxQaAIeeWM2wd/BHxepwqZ+6JTTEFk6O962WlP/X3kLG0B2KuU7almBzxsCXu/9OJTTrXzKi4ogjdt24ErsR6X8uNofD6tpRpnds3/FgkYiPA6qgPq+BOUbSmmpuIzticdMhLQvJtNqSwy7gI+B
    clientSecret: AgCKVBdCCWjf/NhCtulltuvkVYC31xBm2/uct5GrVMG3Sy8BgIc9/3XTjmtoO7K8t5CdLpa7gqaV63eKcSZOGn4NjI8v3OTeZFojb7g0k/sKWiuGHArIpplNW5UKnH6eHq5gSOXp/9kBaJaFsNoDtkz5EYYiayLRF+mn9/yfGOGzGUYPRAyZ8iWMgv4nArTnQuiSFHFTjOwj9vExd+i7rxiH77J9N1UTlPXW0RUMUUYnYcMGIbSaBmqcF93IybApb6Iyj57Yt6msINGghglNp12lTYb1NS6wmyzHEB25v2z0raZ8zAySq1KPvIErmYxY1UzbQndE8GGQm6vz1upeldTFn2MClPBEVhooYnEHoKTfQ2W/AcsbhYoSSAR80Ui3hOg7bUruBxwYhjBmMt0gf226PGU95zsKfo+YpL0n8cWKgcuWQQkxTsOsctth5uM00t2EP3Hdcouzg/bvRCNCW7DpV1wsIJw3FzG5K7K8ojVIPWVkI0k3Wo0wBVhLfvV4eId9QAFKGh6/nLbu0jUQxqAmP09/QmA7b/2wgEeFFSuBYwgi7UvNV08c82Hv9bJ8ln4hwQn/u8ObE+hlukJFIku9EHATzOpqHTgVFgRq+BundVK57nrS7bOjxGxrQXo1gPUTUQvLDJ9oje/czdxiVNraIcs7/coumF/ymXvTpaq8fxozj6Yu637LwuIRQMdjOtAeZgndIoQhwE4Su8cZHLiJ98KhgVgae5yCDxmw1lTgxXdula3Q0rHZ3IJ5s617tYFope243R7CqX+cmwazNHVyfrg=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
