apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - source-oci-base.yaml
  - kustomization-base.yaml
  - source-oci-cloudflared.yaml
  - kustomization-cloudflared.yaml
  - source-oci-whoami.yaml
  - kustomization-whoami.yaml
