{
  "apiVersion": "v1",
  "items": [
    {
      "apiVersion": "helm.toolkit.fluxcd.io/v2",
      "kind": "HelmRelease",
      "metadata": {
        "labels": {
          "kubenix/hash": "d50973dc7c8031452f3bcea9be815bf7a20bde6f"
        },
        "name": "cloudflared",
        "namespace": "cloudflare"
      },
      "spec": {
        "chart": {
          "spec": {
            "chart": "cloudflared",
            "interval": "24h",
            "sourceRef": {
              "kind": "HelmRepository",
              "name": "cloudflared",
              "namespace": "flux-system"
            },
            "version": "2.2.7"
          }
        },
        "interval": "24h",
        "values": {
          "ingress": [
            {
              "hostname": "whoami.andrewlee.cloud",
              "service": "http://whoami.whoami.svc.cluster.local:80"
            },
            {
              "hostname": "hubble.andrewlee.cloud",
              "service": "http://hubble-ui.kube-system.svc.cluster.local:80"
            },
            {
              "service": "http_status:404"
            }
          ],
          "resources": {
            "limits": {
              "cpu": "200m",
              "memory": "128Mi"
            },
            "requests": {
              "cpu": "100m",
              "memory": "64Mi"
            }
          },
          "tunnelConfig": {
            "name": "cloud"
          },
          "tunnelSecrets": {
            "existingConfigJsonFileSecret": {
              "name": "cloudflared-config-json-file-secret"
            },
            "existingPemFileSecret": {
              "name": "cloudflared-cert-pem-file-secret"
            }
          }
        }
      }
    },
    {
      "apiVersion": "helm.toolkit.fluxcd.io/v2",
      "kind": "HelmRelease",
      "metadata": {
        "labels": {
          "kubenix/hash": "d50973dc7c8031452f3bcea9be815bf7a20bde6f"
        },
        "name": "vcluster-helsinki",
        "namespace": "vcluster-helsinki"
      },
      "spec": {
        "chart": {
          "spec": {
            "chart": "vcluster",
            "interval": "24h",
            "sourceRef": {
              "kind": "HelmRepository",
              "name": "vcluster",
              "namespace": "flux-system"
            },
            "version": "0.34.0"
          }
        },
        "interval": "24h",
        "values": {
          "sync": {
            "fromHost": {
              "nodes": {
                "enabled": true,
                "selector": {
                  "labels": {
                    "role": "server"
                  }
                }
              }
            }
          }
        }
      }
    }
  ],
  "kind": "List",
  "labels": {
    "kubenix/hash": "d50973dc7c8031452f3bcea9be815bf7a20bde6f",
    "kubenix/k8s-version": "1.35",
    "kubenix/project-name": "helsinki"
  }
}
