{
  "apiVersion": "v1",
  "items": [
    {
      "apiVersion": "v1",
      "kind": "Namespace",
      "metadata": {
        "labels": {
          "kubenix/hash": "9d392fc102ef4fd20847bc463b39950b027cca92"
        },
        "name": "garage"
      }
    },
    {
      "apiVersion": "v1",
      "kind": "Namespace",
      "metadata": {
        "labels": {
          "kubenix/hash": "9d392fc102ef4fd20847bc463b39950b027cca92"
        },
        "name": "gitlab"
      }
    },
    {
      "apiVersion": "helm.toolkit.fluxcd.io/v2",
      "kind": "HelmRelease",
      "metadata": {
        "labels": {
          "kubenix/hash": "9d392fc102ef4fd20847bc463b39950b027cca92"
        },
        "name": "cloudflared",
        "namespace": "cloudflare"
      },
      "spec": {
        "chart": {
          "spec": {
            "chart": "cloudflared",
            "interval": "24h",
            "sourceRef": {
              "kind": "HelmRepository",
              "name": "cloudflared",
              "namespace": "flux-system"
            },
            "version": "2.2.7"
          }
        },
        "interval": "24h",
        "values": {
          "ingress": [
            {
              "hostname": "whoami.andrewlee.cloud",
              "service": "http://whoami.whoami.svc.cluster.local:80"
            },
            {
              "hostname": "hubble.andrewlee.cloud",
              "service": "http://hubble-ui.kube-system.svc.cluster.local:80"
            },
            {
              "service": "http_status:404"
            }
          ],
          "resources": {
            "limits": {
              "cpu": "200m",
              "memory": "128Mi"
            },
            "requests": {
              "cpu": "100m",
              "memory": "64Mi"
            }
          },
          "tunnelConfig": {
            "name": "cloud"
          },
          "tunnelSecrets": {
            "existingConfigJsonFileSecret": {
              "name": "cloudflared-config-json-file-secret"
            },
            "existingPemFileSecret": {
              "name": "cloudflared-cert-pem-file-secret"
            }
          }
        }
      }
    },
    {
      "apiVersion": "helm.toolkit.fluxcd.io/v2",
      "kind": "HelmRelease",
      "metadata": {
        "labels": {
          "kubenix/hash": "9d392fc102ef4fd20847bc463b39950b027cca92"
        },
        "name": "garage",
        "namespace": "garage"
      },
      "spec": {
        "chart": {
          "spec": {
            "chart": "garage",
            "interval": "72h",
            "sourceRef": {
              "kind": "HelmRepository",
              "name": "garage",
              "namespace": "flux-system"
            },
            "version": "2.3.2"
          }
        },
        "values": {
          "deployment": {
            "replicaCount": 1
          },
          "garage": {
            "compressionLevel": 19,
            "metadataAutoSnapshotInterval": "2 days",
            "replicationFactor": 1
          },
          "image": {
            "tag": "2.3.0"
          },
          "nodeSelector": {
            "machine": "kamrui-p1"
          },
          "persistence": {
            "data": {
              "size": "50Gi",
              "storageClass": "local-path"
            },
            "meta": {
              "size": "5Gi",
              "storageClass": "local-path"
            }
          },
          "resources": {
            "limits": {
              "cpu": "2",
              "memory": "4Gi"
            },
            "requests": {
              "cpu": "100m",
              "memory": "128Mi"
            }
          }
        }
      }
    },
    {
      "apiVersion": "postgresql.cnpg.io/v1",
      "kind": "Cluster",
      "metadata": {
        "labels": {
          "kubenix/hash": "9d392fc102ef4fd20847bc463b39950b027cca92"
        },
        "name": "postgres",
        "namespace": "gitlab"
      },
      "spec": {
        "instances": 1,
        "resources": {
          "limits": {
            "cpu": "2",
            "memory": "4Gi"
          },
          "requests": {
            "cpu": "100m",
            "memory": "128Mi"
          }
        },
        "storage": {
          "size": "150Gi",
          "storageClass": "local-path"
        },
        "walStorage": {
          "size": "15Gi",
          "storageClass": "local-path"
        }
      }
    },
    {
      "apiVersion": "helm.toolkit.fluxcd.io/v2",
      "kind": "HelmRelease",
      "metadata": {
        "labels": {
          "kubenix/hash": "9d392fc102ef4fd20847bc463b39950b027cca92"
        },
        "name": "valkey",
        "namespace": "gitlab"
      },
      "spec": {
        "chart": {
          "spec": {
            "chart": "valkey",
            "interval": "72h",
            "sourceRef": {
              "kind": "HelmRepository",
              "name": "valkey",
              "namespace": "flux-system"
            },
            "version": "0.9.4"
          }
        },
        "interval": "72h",
        "values": {
          "dataStorage": {
            "className": "local-path",
            "enabled": true,
            "nodeSelector": {
              "machine": "kamrui-p1"
            },
            "requestedSize": "8Gi"
          },
          "image": {
            "tag": "9.0.2"
          },
          "initResources": {
            "limits": {
              "cpu": "1",
              "memory": "1Gi"
            },
            "requests": {
              "cpu": "100m",
              "memory": "128Mi"
            }
          },
          "resources": {
            "limits": {
              "cpu": "1",
              "memory": "1Gi"
            },
            "requests": {
              "cpu": "100m",
              "memory": "128Mi"
            }
          }
        }
      }
    }
  ],
  "kind": "List",
  "labels": {
    "kubenix/hash": "9d392fc102ef4fd20847bc463b39950b027cca92",
    "kubenix/k8s-version": "1.34",
    "kubenix/project-name": "helsinki"
  }
}
