{
  "apiVersion": "v1",
  "items": [
    {
      "apiVersion": "v1",
      "kind": "Namespace",
      "metadata": {
        "labels": {
          "kubenix/hash": "587cdc3eac924d469069c8eb3e78772c2f98e09a"
        },
        "name": "cloudflare"
      }
    },
    {
      "apiVersion": "v1",
      "kind": "Namespace",
      "metadata": {
        "labels": {
          "kubenix/hash": "587cdc3eac924d469069c8eb3e78772c2f98e09a"
        },
        "name": "whoami"
      }
    },
    {
      "apiVersion": "source.toolkit.fluxcd.io/v1",
      "kind": "HelmRepository",
      "metadata": {
        "labels": {
          "kubenix/hash": "587cdc3eac924d469069c8eb3e78772c2f98e09a"
        },
        "name": "cloudflared",
        "namespace": "flux-system"
      },
      "spec": {
        "interval": "24h",
        "url": "https://community-charts.github.io/helm-charts"
      }
    },
    {
      "apiVersion": "apps/v1",
      "kind": "DaemonSet",
      "metadata": {
        "labels": {
          "kubenix/hash": "587cdc3eac924d469069c8eb3e78772c2f98e09a"
        },
        "name": "whoami",
        "namespace": "whoami"
      },
      "spec": {
        "selector": {
          "matchLabels": {
            "app": "whoami"
          }
        },
        "template": {
          "metadata": {
            "labels": {
              "app": "whoami"
            }
          },
          "spec": {
            "containers": [
              {
                "args": [
                  "--port",
                  "8080"
                ],
                "image": "traefik/whoami",
                "name": "whoami",
                "ports": [
                  {
                    "containerPort": 8080
                  }
                ],
                "securityContext": {
                  "allowPrivilegeEscalation": false,
                  "capabilities": {
                    "drop": [
                      "ALL"
                    ]
                  }
                }
              }
            ],
            "securityContext": {
              "fsGroup": 1000,
              "runAsGroup": 1000,
              "runAsNonRoot": true,
              "runAsUser": 1000,
              "seccompProfile": {
                "type": "RuntimeDefault"
              }
            }
          }
        }
      }
    },
    {
      "apiVersion": "v1",
      "kind": "Service",
      "metadata": {
        "annotations": {
          "service.cilium.io/global": "true"
        },
        "labels": {
          "kubenix/hash": "587cdc3eac924d469069c8eb3e78772c2f98e09a"
        },
        "name": "whoami",
        "namespace": "whoami"
      },
      "spec": {
        "ipFamilies": [
          "IPv4",
          "IPv6"
        ],
        "ipFamilyPolicy": "PreferDualStack",
        "ports": [
          {
            "port": 80,
            "targetPort": 8080
          }
        ],
        "selector": {
          "app": "whoami"
        },
        "type": "ClusterIP"
      }
    }
  ],
  "kind": "List",
  "labels": {
    "kubenix/hash": "587cdc3eac924d469069c8eb3e78772c2f98e09a",
    "kubenix/k8s-version": "1.35",
    "kubenix/project-name": "shared"
  }
}
