---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: agent-secrets
  namespace: ai-production-workshop
spec:
  encryptedData:
    OPENAI_API_KEY: AgBsWgIoSW/yiOGwI0aPcq+zv579tpNEFch1NU/ZsEsJEjH4tfVtRsQH8hBtzIkhVnkmqv6Y2rYKbH/ZlJNPUwf6o9T15YjnyskSNhrDsIs0Ws7Lie6b6UQWOOiHw9w/CD+nvO1/2fzf27+rVVIOrE+fOhAkXU5PrzzoBzo4R5EFO0qZcmfT7DZZvVPG8LizBGYAxfWBNuBgPGlCuOZFICKD/q97cas7+LwNsASwrY+e3e9VZXhmDorWsJMf8HdixLDPlLUp7fD8XPh8O6zPOaW45NBIArIC4tK1/31Q02niSAy35Rq5tOd2cTjpYixi2pq/Lfwq5UsrephRAJGoejhYCeW84Q2sWY+pZL6pFY38qqi6F/wQg8vHaVUJ3+JJT/8e/L4T7g8X8p4vg68WNyNCSg+0b2CHk3kOA+g1G1FaTxn++KjY9MB6Cm3NL/prB7BqGqN1XwRvQ6VhGR+nG2omEpesjKgIXNe9OG4pFPBI6ixH6GWZ1ldzF7Kaqc0tpyEM3jvk+ZaJWn/cKAvqiZsCzTR30ZHquGewAyfBRDPDriOF0IwfJANypHBEWsiaADBjyZHXrvw0mwRqKI4iNeydj73ZZN8vt9knKzdT2hYS3uuwp5dfuI0sP+4GzTCNWY17IYcef3+zhlxuc9kkWNcmk0PPxqhEmwiscMQMVMG44ueUD8v7syTTmWbHf0SQpQBDLLBFSm+B/Q3zl/7PhcTLU09EJTBSR05muPsiSJr/Bu+DMBEe7JhPyERxFd/F03Ywjzr+ov+0Fhzfj/bhOSlY/53lhZ5sMJ0HoYHFZWIaPePjz+GP0ijRZVCtjHYCKl9mGfl9euMVM/150+4e9b5r8g0QT+Wrt0ylRmKmcNW3n/Mqo5V8JlYQmDgGQ5b1BLqbNiwyL/9V0+BoVNml1qCmQziaaA==
  template:
    metadata:
      name: agent-secrets
      namespace: ai-production-workshop
