---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: agent-secrets
  namespace: ai-production-workshop
spec:
  encryptedData:
    OPENAI_API_KEY: AgAOW9zLs5rGWJfWwClNDB4t6I4URawd/EotXAwTiu4NG5/IlTlmaZliaPVpVRq0jWGNw7SXmF6+O8WSsfDAnPWUvBYcZoU3EiNK+9JHoHj2dicLipdwdM8InzoGWdna+IDsajugWMw3CT+CJFazkK/mtXgNNLv3nv9Xp0eX/lbRGJ/P5RmMr1XFRmrF/ZsxH0pL3fjAV2sJliUtvHD6Y8Czsf4+YNVWbObHzC0fNslZvf0qv2HWxSJd3wcMaO7SmsYVXbis4pzP/SACR3axhJ5+Qb6WkIyImCyFZg/yXuKEAAnaAIoJlP2PND1wUXjq7iWJXAupR69CFGtUOwNaAeRmBUWHjgANQvv4U5vr13LFit9l/0WXJYJBw14OD88pLbktEppfpzQaFASAgu3tdCJRkHs+SjDKMp2IJoLCONt7Ve69NjEJ+Ab54CGC90mdoi0qQCPjO0kb1pWQGbZRWdHrgFSSbDTh2xQbBw3QgvgIFa/tA9sIgd1RLqQG9E6jvA8jg4W8+/CcVDXznh/VpzThDqA03+7t6Ju4agR14WuD0MxH29yKOrnaoIrK2zN7rmboIHN4nT0oGgwmL8bJdPtziwukGc0yjwKO409QjqN9+hXbzkkDj0tHL6eCYQ9SDoYgC2FXi9by6tpGdQ6GTDDYnnDc1dIqEBIptuinkPHT+aIYK4Mhgc5A5XFOs+9v/QbtZ+Dkpo7U32QKm2QFezTDKK2yeja6gZQoW964YsVeGl59sSQxmGmk56N9aErizv/4UoVEswADibCoD9aiMJhkhoAoH5LqFQRVpe2Pss2qc2xHsLlMP/qAV0ybWNgWT8WMBF5oeAjiy/KedU1W6g6iRaujjNQPvBza2WSlZrqY/jeVAZUM4sV5p2/3Gvh5Y6kam3XLxW6xfRaiirwyyTaXY4G+Zw==
  template:
    metadata:
      name: agent-secrets
      namespace: ai-production-workshop
