---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgAW/FQlTI+X8V9Ea/gVOgau4gCh6Reki5HhoMw4NWddxf5jW8tLX/DH7wupRKoSPQ3pOD5oeN7bjUUjBNPjM5SzftONscMaUm0p40pfJsLGlQcE+BlsNqX8f+fMV+Zq1i6iJW8Yzl7JApbtKRm3NSiDWBxonm/B99e67CXPRpGDxbEDv/9W79pJ7JKAvIIBgIWvaDeJHDbFP1aGOBQVXtEHsGYApzK1ijWPUBDdxZAu4uKAj+f3pVNYN/mvpug/Sym0j9hPKHLUu3ck1w2tahXoVp03I435DTcSY+/bjOVeWFWy1GNR5tK3UzvvIkVwJl/LaoeRUY2a/3qSWfASf+3aorvM+iyTse6mjpAo1VgR6L68A9fRB6j94xBaW0s08rdW4+raYFVeSBgaZCqAlLdpgDGhutEGK/C9qhUVBZFDCQjwqKXNbwdY30a36sjP/pOwR4UNl/As1Z1cG2pxDladwOqyxc3C/LYRQrqGzjqJ+lve6v8MnLMMqsKyYXT47YVXcxLYroSp8FkWc5wO5wKg4fG0jb9iSe6j7+cbQVUifon1XtxzKEoflfs8v6l5Oc0g2GTENVaC7B28Jih+9LnWLbXdo0SIn3pVyhN446ple2LEWaVmWKIlFlBLKeZUDbOM5hf5HZaqHmH2mb/d8sjCwOZmUz9sT6e8Rl1wJx7azEaFTDVc/jCLtb8itfenMzvV/t0BWe6zM2D//ZZUUD4fmMggo5PgS/+dXOKUgSMXxULn5j6hq4f98hnOGlw80jKWueQVlKU2GlVJPmel44fbsPZMSU8+QKvGoky2c6CPfccgH03K2vkVsLpTZOiVuVsFQIDfmGgpvM2Gn9AP6/96Nyz1zU2zrDVTcgjeXBRIUQrNt1ktSfQQSrRKECyeK1KECx9RFzX9HYThLJOUeSxfWjE3DpePKy/uTtTCQ+cA
  template:
    metadata:
      name: cloudflared-credentials
      namespace: cloudflare
