---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-cert
  namespace: cloudflare
spec:
  encryptedData:
    cert.pem: AgB5fygnjXRu2KijYPRizEoa01T0JbpPJrTexlfqHIlIBH+KSGMOl2TN6QMCyIA312uGC7o1tg4YWAmpdizkottWeAwUBXqICZXwsG5ZpsEnba2IFJycvibgaYL/pqe/30QxFLXPL15TVx/ktAX5UALeX398PIeeLnPluusCr0wgrmA+RP3Z/CGfOlqgT6mgBYGk+6NP75UuItdU7eU329baHSrVWfmwB0IsZHqNVqz4aFKHD4twdXpqhRGOSYVeEiRuQtgUYQ+0zC/lY7F7ftmSeSArXranYQwVog6fm1REsFuJT3PEOLyK7s8ZLtF0mr582DKCPjrKChSPo+Q6QpFBph1+fzs5PmEhdKlUhgrQ07WpexWBi0v/QcLdVUb/Eo4VNo7fDabVTu5+181kA7v7sIfvJzE51LzDR8vM5pctg40iQaXoAg4jLPcWhoXe5b60qqBq2W7I1fo3eaeaGXrdgjod/tg+Ugk/twLnhbqRrpUNCARwTp3202AhHjy9c2JhnMy7zHhLQ503Qn7qVr2XdB051OaZqRCs98p7EyFmICfakmYnb4eaSDL7pnwgWpLVerMPKm3muHsGxop7Q8dEIkN/wkQeU7Psig/1IXH7vSVeP61izQCYnbjE5xvXpuB80JYrMV9NDtQTYM+Fe16pH9w0/4kDCBcG1gIOmhYwkfS1lNmsTmb3jFTK/k9vPgquwILGjqbMYdwW5L9j2sVbrOiqlxK+F4NspbasUMwWeQuozCPZv+J7rvbbuoBb5VjYZankveUeJHjTlo4CozIEEmDbtQv6zHnEJcJhbWXkrGhNLebQih4lFD3CPGrRvGXp4PAnLmupTPGv1qf8rLcR5C3m9cK7C38x87jlxNJOtb3BZ097F+tk+UnBKwGZyESIDHcXuMtCD7+BHxlZW90qj6KcnntMGaxSF5fz4gbQyX7V/n05LXhDOFhv1QDQ8HLHwDmrejfttaVuptUS7NxxR5dvtTF8CmMoO0lakL48uHLT9KRAb+zgniPkpsc33bMRAspjdKLFMGhCKAFA9EOgJdHswV+vX+Sq/1wSM7mwp3+NFncBvvtXufQ=
  template:
    metadata:
      name: cloudflared-cert
      namespace: cloudflare
