---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 12h
  url: oci://ghcr.io/andrewthomaslee/home/oci/helm/cnpg
  ref:
    tag: latest
