---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgBISbTC4lrb+1M5DIhDxxDCBJ6py2CYt/ySyIxN3t01kBY0F2ST5JpHDwB1fUGYJxVCnsN/WRZj959ef7zYVzjVPe7tYwIOxHS18F9fHCKA/Mr94ugXPQfMd6trkClYIKaWXTGpnS1oww8n407HwLeF+YBcqWfB9m2bpov4s7fdCmqhrD3v7U6AUBDP9TR3DMESXmcV1fYHRjR6MYnvUuApEjwBDBvjRLCpHhoXgpMwUDD69CqYomY3H9p/iRCO1k2tim7TO04fBEEfZwaciu8P9rh3NweOyRywFOeJIwteu8EkklU5Qtq23kNB0+nU2U6t3kF2C6Et2O1ZdCNO13MAdPUDR5GmmNZMv6fxuKHyzwOhcBCne0lzvvyYQPCHvZGhE0faHXCgWu0kpF2KRsGt/rYBumVfdVMuVdcqPcroVZfc2OrWjR4Y/yFz/ryVyWghk+/biW1TRJob+y8F54wQgP35TAd0GgzhOXLHbT4TldOjc8RjGvS6cBjRjUtdMFc9H38Kn7U4/p63GaEwxFPVG7hYQOFPnzcIRn2GYz9OF9pvtguU2mlI9WAbXL1ubjYN8PCbZOP3olWSjglEO5gb2jiCR0qEM+8jtu7mbPu+wON0KGZiTBOeoY5AChQJJJ2WBWX2N+kiR7zCMYzvf5jBLWvhRE3zz7GGcmQMt22uREMeva2iEVMNAtrrF1binuNVN1gs2zM3PfrWFCUxvEINq/TIOjmwPFV18HE6iD0srxBYMtIVxVfqNuUfYhPSMTpFssqWWMIIc6StqpPPukMbKAn2Cms3kcXYnXepecUF+R2LZ78uq4FIxscI2ASQHi7QwsHq402UfqPe2YYNVos5Np6wbwTwloZ4hpc34t9miLppclgH2BEV1wezjJ0Tru0uPEFBnnbLDEUPDF0yNa0x2OaDu+tJBfn6PuOQy2DP
  template:
    metadata:
      name: cloudflared-credentials
      namespace: cloudflare
