apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - source-oci-cloudflared.json
  - kustomization-cloudflared.json
  - ingress-capacitor.yaml
patches:
  - target:
      kind: Kustomization
      name: oci-cloudflared
      namespace: flux-system
    patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: oci-cloudflared
        namespace: flux-system
      spec:
        patches:
          - target:
              kind: ConfigMap
              name: cloudflared
              namespace: cloudflare
            patch: |-
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: cloudflared
                namespace: cloudflare
              data:
                config.yaml: |
                  tunnel: andrewlee.fun
                  credentials-file: /etc/cloudflared/creds/credentials.json
                  originRequest:
                    connectTimeout: 30s
                  
                  ingress: 
                    - hostname: "whoami.andrewlee.fun"
                      service: http://whoami.whoami.svc.cluster.local:80
                    - hostname: "hubble.andrewlee.fun"
                      service: http://hubble-ui.kube-system.svc.cluster.local:80
                    - hostname: "*.andrewlee.fun"
                      service: http://traefik.kube-system.svc.cluster.local:80
                    - service: http_status:404
                  
                  metrics: 0.0.0.0:2000
                  metrics-update-freq: 5s
                  
                  autoupdate-freq: 24h
                  no-autoupdate: true
                  
                  grace-period: 30s
                  
                  retries: 5
                  
                  # auto, http2, h2mux, quic
                  protocol: auto
                  
                  # info, warn, error, fatal, panic
                  loglevel: info
                  transport-loglevel: warn
