site_name: Dendritic Determinate Nix Flake # TODO: change to your project name
site_author: Andrew Thomas Lee # TODO: change to your name
site_url: https://home.andrewlee.cloud # TODO: change to your domain
repo_url: https://github.com/andrewthomaslee/home # TODO: change to your repo
repo_name: andrewthomaslee/home # TODO: change to your repo

nav:
  - Home: index.md
  - Clan Services:
      - Overview: clanServices/index.md
  - Flake Parts:
      - Overview: flake-parts/index.md
      - Default: flake-parts/default.md
      - Dev Shells: flake-parts/devShells.md
      - Profiles: flake-parts/profiles.md
      - Kubenix: flake-parts/kubenix.md
      - Apps:
          - Overview: flake-parts/apps/index.md
          - Update Flake Show: flake-parts/apps/update-flake-show.md
          - Flux Bootstrap: flake-parts/apps/flux-bootstrap.md
          - Fetch Kubeconfig: flake-parts/apps/fetch-kubeconfig.md
          - TMP Pod: flake-parts/apps/tmp-pod.md
      - Packages:
          - Overview: flake-parts/packages/index.md
      - Home Modules:
          - Overview: flake-parts/homeModules/index.md
          - Docker: flake-parts/homeModules/docker.md
          - K9s: flake-parts/homeModules/k9s.md
          - Shell: flake-parts/homeModules/shell.md
          - SSH: flake-parts/homeModules/ssh.md
          - Starship: flake-parts/homeModules/starship.md
          - XDG: flake-parts/homeModules/xdg.md
      - NixOS Modules:
          - Overview: flake-parts/nixosModules/index.md
          - Clan: flake-parts/nixosModules/clan.md
          - Docker: flake-parts/nixosModules/docker.md
          - Networking: flake-parts/nixosModules/networking.md
          - Nix: flake-parts/nixosModules/nix.md
          - OpenSSH: flake-parts/nixosModules/openssh.md
          - Tailscale: flake-parts/nixosModules/tailscale.md
          - MOTD: flake-parts/nixosModules/motd.md

plugins:
  - glightbox
  #- info # only useful for debugging
  - offline
  - search
  - tags

theme:
  font: false

  language: en

  name: material

  icon:
    repo: fontawesome/brands/github

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: grey
      accent: blue
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference