site_name: Andrew's Home Monorepo
site_author: Andrew Thomas Lee
site_url: https://home.andrewlee.cloud
repo_url: https://github.com/andrewthomaslee/home
repo_name: andrewthomaslee/home

nav:
  - Home: index.md
  - Minecraft:
      - Overview: minecraft/index.md
      - mc.andrewlee.fun: minecraft/mc-andrewlee-fun.md
  - Clan Services:
      - Overview: clanServices/index.md
      - Exports: clanServices/exports.md
      - Cluster Mesh: clanServices/cluster-mesh.md
      - Kubernetes: clanServices/kubernetes.md
  - Flake Parts:
      - Overview: flake-parts/index.md
      - Default: flake-parts/default.md
      - Dev Shells: flake-parts/devShells.md
      - Profiles: flake-parts/profiles.md
      - Kubenix: flake-parts/kubenix.md
      - Apps:
          - Overview: flake-parts/apps/index.md
          - Update Flake Show: flake-parts/apps/update-flake-show.md
          - Update Minecraft Mods: flake-parts/apps/update-minecraft-mods.md
          - Kubernetes:
              - Overview: flake-parts/apps/kubernetes/index.md
              - Fetch Kubeconfig: flake-parts/apps/kubernetes/fetch-kubeconfig.md
              - Flux Bootstrap: flake-parts/apps/kubernetes/flux-bootstrap.md
              - Tmp Pod: flake-parts/apps/kubernetes/tmp-pod.md
      - Packages:
          - Overview: flake-parts/packages/index.md
          - Playit: flake-parts/packages/playit.md
      - Home Modules:
          - Overview: flake-parts/homeModules/index.md
          - Bun: flake-parts/homeModules/bun.md
          - Direnv: flake-parts/homeModules/direnv.md
          - Docker: flake-parts/homeModules/docker.md
          - Firefox: flake-parts/homeModules/firefox.md
          - Ghostty: flake-parts/homeModules/ghostty.md
          - Git: flake-parts/homeModules/git.md
          - Go: flake-parts/homeModules/go.md
          - K9s: flake-parts/homeModules/k9s.md
          - KSSHAskPass: flake-parts/homeModules/ksshaskpass.md
          - Media: flake-parts/homeModules/media.md
          - Neovim: flake-parts/homeModules/neovim.md
          - Password Store: flake-parts/homeModules/password-store.md
          - Shell: flake-parts/homeModules/shell.md
          - SSH: flake-parts/homeModules/ssh.md
          - Starship: flake-parts/homeModules/starship.md
          - UV: flake-parts/homeModules/uv.md
          - VS Code: flake-parts/homeModules/vscode.md
          - XDG: flake-parts/homeModules/xdg.md
          - Tmux: flake-parts/homeModules/tmux.md
      - NixOS Modules:
          - Overview: flake-parts/nixosModules/index.md
          - Bluetooth: flake-parts/nixosModules/bluetooth.md
          - Clan: flake-parts/nixosModules/clan.md
          - Docker: flake-parts/nixosModules/docker.md
          - KDE: flake-parts/nixosModules/kde.md
          - Minecraft: flake-parts/nixosModules/minecraft.md
          - Networking: flake-parts/nixosModules/networking.md
          - Nix: flake-parts/nixosModules/nix.md
          - OpenSSH: flake-parts/nixosModules/openssh.md
          - Sound: flake-parts/nixosModules/sound.md
          - Storage Box: flake-parts/nixosModules/storagebox.md
          - Tailscale: flake-parts/nixosModules/tailscale.md
          - Wayland: flake-parts/nixosModules/wayland.md
          - MOTD: flake-parts/nixosModules/motd.md

plugins:
  - glightbox
  #- info # only useful for debugging
  - offline
  - search
  - tags

markdown_extensions:
  - attr_list

theme:
  font: false

  language: en

  name: material
  favicon: assets/brand/andrewthomaslee-transparent-logo.png

  icon:
    repo: fontawesome/brands/github

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: grey
      accent: blue
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference