---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgBRC44gNmfd7mG/Ta1ZkBH9RkfIL1cObl/TxnXlC7uWpSzwAUHBysqXnYXwDf0DyuuSQt9HwjRTnmUBEuEFxZcDX72TL1iAtxlifcLsdfORHnnIRjAnyuc6zu7SyXNn5JPhCltA629c/nAGVxsNlpCC1I25Zhf6dmmX1aLVoKXWz/2i25L2Dby3d+uOm9URexK7B2PWba5JlWQO/AmUa6mj0o/dWe02nDaYZQu+f3umF28P4ZJact70+cfEKaLevjvQw64rqcm8UcV7DfMth76AuUzRu3uoh3dsg77/kYoCKcrLFb50XeXT6/fxQET+DCx8Frf9xSUTAmsEf15+rS97xgRSva39OP2HIgRD6KTu4NaOIj0MAgqgWVWmCMlPwmfbGDlD2hsR2EZssCEtryK43/WLfu2pariildp6fYs1wqP+PMDyD3CxgggIC/9LDzfNr4CVYqC91PEmp0L1urzF+2622KbKbwWUq4SzK57kAcdmV3rMSJUfpoMq3jodaiPsA8z0ZM7pwK/dDNdMpv8C3JncbndR+uTYNlr8UQLfPlvbVujM/X9z0uX0HP98ULu7j0yqhsVO2c++mGbb12JN7gLy4l+Nx9nAo8bWBDVTWq8sOYkcDkoGSb2mqFppPo1cCRmQwjiFva+Hw1j8fwvUg6+D67BS/NXacmXqv/C+bxSZUrWCn3V6PY3zif5BPLzBl3xtbq7lWy+qRuQEiR5N7tHpRhZIxygnGPHxBQ+2P5U9wGZZ+YOExT2rVkwwXXHMpj+xB/Ec4beWNOYL7gXu6Xa0qArwqpIoVuqlJaIA1gJxiRPsd6o8trtcqTKSVUBAgtjeDgPDUPn4VvBvtwv2SUIB6KkiHDRx
  template:
    metadata:
      name: discord-webhook-url
      namespace: flux-system
