name: Reusable Build Machines
on: workflow_call
jobs:
  build-machines:
    strategy:
      fail-fast: false
      matrix:
        machine: [nixos, ghost, kamrui-h1, beelink, inuc-celeron, inuc-i5, hp-notebook]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          persist-credentials: true

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Build Machine ${{ matrix.machine }}
        run: nix build .#nixosConfigurations.${{ matrix.machine }}.config.system.build.toplevel
