name: CI
permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flake-check:
    uses: ./.github/workflows/_flake-check.yml
