name: CI

on:
  push:
    branches:
      - main


jobs:
  flake-check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          persist-credentials: true

      - name: Install Nix  
        uses: DeterminateSystems/determinate-nix-action@main

      - name: Nix Cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Flake Checker
        uses: DeterminateSystems/flake-checker-action@main
        with:
          check-owner: false
          check-supported: false
          fail-mode: true

      - name: Nix Flake Check
        run: nix flake check --show-trace

  build-machines:
    needs: flake-check
    strategy:
      matrix:
        machine: [nixos, ghost, kamrui-p1, inuc-celeron, inuc-i5, hp-notebook, hel-1, hel-2, hel-3]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          persist-credentials: true

      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main

      - name: Build Machine ${{ matrix.machine }}
        run: nix build .#nixosConfigurations.${{ matrix.machine }}.config.system.build.toplevel

  build-artifacts:
    needs: flake-check
    strategy:
      matrix:
        artifact: [devShell, tofu]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          persist-credentials: true

      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main

      - name: Build ${{ matrix.artifact }}
        run: nix build .#${{ matrix.artifact }}

  publish:
    needs: 
      - build-machines
      - build-artifacts
      - flake-check
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          persist-credentials: true

      - name: Install Nix  
        uses: DeterminateSystems/determinate-nix-action@main

      - name: Nix Cache
        uses: DeterminateSystems/flakehub-cache-action@main
      
      - name: Build MkDocs
        run: nix build .#documentation --show-trace

      - name: Setup Pages
        uses: actions/configure-pages@v6.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: './result'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5.0.0

      - name: Publish to FlakeHub
        uses: DeterminateSystems/flakehub-push@main
        with:
          visibility: public
          name: andrewthomaslee/home
          include-output-paths: true
          rolling: true
          rolling-minor: 3
