name: Release

permissions:
  id-token: write
  contents: write
  packages: write
  pages: write

on:
  workflow_dispatch:

jobs:
  flake-check:
    uses: ./.github/workflows/_flake-check.yml

  build-machines:
    needs: flake-check
    uses: ./.github/workflows/_build-machines.yml

  build-artifacts:
    needs: flake-check
    uses: ./.github/workflows/_build-artifacts.yml

  build-oci:
    needs: flake-check
    uses: ./.github/workflows/_oci.yml

  docs:
    needs: [build-machines, build-artifacts, build-oci, flake-check]
    uses: ./.github/workflows/_docs.yml

  push:
    needs: [build-machines, build-artifacts, build-oci, flake-check]
    uses: ./.github/workflows/_flakehub.yml

  release:
    needs: [docs, push]
    uses: ./.github/workflows/_release.yml
    secrets: inherit

  oci:
    needs: release
    uses: ./.github/workflows/_oci.yml
    with:
      push: true
      tag: ${{ needs.release.outputs.tag }}
    secrets: inherit
