name: Release

permissions:
  id-token: write
  contents: write
  packages: write
  pages: write

on:
  workflow_dispatch:

jobs:
  pre-flight:
    uses: ./.github/workflows/_flake-check.yml

  machines:
    needs: pre-flight
    uses: ./.github/workflows/_build-machines.yml

  artifacts:
    needs: pre-flight
    uses: ./.github/workflows/_build-artifacts.yml

  mkdocs:
    needs: [machines, artifacts]
    uses: ./.github/workflows/_docs.yml

  flakehub:
    needs: [machines, artifacts]
    uses: ./.github/workflows/_flakehub.yml

  tag:
    needs: [mkdocs, flakehub]
    uses: ./.github/workflows/_release.yml
    secrets: inherit
