apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - source-oci-home-oci-packages-whoami.json
  - kustomization-home-oci-packages-whoami.json
patches:
  - patch: |-
      - op: add
        path: /spec/hostnames/-
        value: "whoami.andrewlee.fun"
    target:
      kind: HTTPRoute
      name: whoami
      namespace: whoami
